//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomIndicatorSet.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomIndicatorSet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Acceleration max.
        /// </summary>
        internal static string AccelMax {
            get {
                return ResourceManager.GetString("AccelMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Acceleration start.
        /// </summary>
        internal static string AccelStart {
            get {
                return ResourceManager.GetString("AccelStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Acceleration step.
        /// </summary>
        internal static string AccelStep {
            get {
                return ResourceManager.GetString("AccelStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accumulated.
        /// </summary>
        internal static string Accumulated {
            get {
                return ResourceManager.GetString("Accumulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accumulation/distribution.
        /// </summary>
        internal static string AD {
            get {
                return ResourceManager.GetString("AD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Average directional movement index.
        /// </summary>
        internal static string ADX {
            get {
                return ResourceManager.GetString("ADX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alert File.
        /// </summary>
        internal static string AlertFile {
            get {
                return ResourceManager.GetString("AlertFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alerts.
        /// </summary>
        internal static string Alerts {
            get {
                return ResourceManager.GetString("Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All Period.
        /// </summary>
        internal static string AllPeriodtxt {
            get {
                return ResourceManager.GetString("AllPeriodtxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Any.
        /// </summary>
        internal static string Any {
            get {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Approximation Alert.
        /// </summary>
        internal static string ApproximationAlert {
            get {
                return ResourceManager.GetString("ApproximationAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ApproximationFilter.
        /// </summary>
        internal static string ApproximationFilter {
            get {
                return ResourceManager.GetString("ApproximationFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ask.
        /// </summary>
        internal static string Ask {
            get {
                return ResourceManager.GetString("Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Above maximum ask color.
        /// </summary>
        internal static string AskAboveColor {
            get {
                return ResourceManager.GetString("AskAboveColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ask color.
        /// </summary>
        internal static string AskColor {
            get {
                return ResourceManager.GetString("AskColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Average true range.
        /// </summary>
        internal static string ATR {
            get {
                return ResourceManager.GetString("ATR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на At start.
        /// </summary>
        internal static string AtStart {
            get {
                return ResourceManager.GetString("AtStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto filter.
        /// </summary>
        internal static string AutoFilter {
            get {
                return ResourceManager.GetString("AutoFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto Filter Period.
        /// </summary>
        internal static string AutoFilterPeriod {
            get {
                return ResourceManager.GetString("AutoFilterPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Average period.
        /// </summary>
        internal static string AveragePeriod {
            get {
                return ResourceManager.GetString("AveragePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BackGround.
        /// </summary>
        internal static string BackGround {
            get {
                return ResourceManager.GetString("BackGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bars.
        /// </summary>
        internal static string Bars {
            get {
                return ResourceManager.GetString("Bars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bars direction.
        /// </summary>
        internal static string BarsDirection {
            get {
                return ResourceManager.GetString("BarsDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bars limit.
        /// </summary>
        internal static string BarsLimit {
            get {
                return ResourceManager.GetString("BarsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Channeel width.
        /// </summary>
        internal static string BBandsWidth {
            get {
                return ResourceManager.GetString("BBandsWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bearish.
        /// </summary>
        internal static string Bearlish {
            get {
                return ResourceManager.GetString("Bearlish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bid.
        /// </summary>
        internal static string Bid {
            get {
                return ResourceManager.GetString("Bid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Above maximum bid color.
        /// </summary>
        internal static string BidAboveColor {
            get {
                return ResourceManager.GetString("BidAboveColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bid color.
        /// </summary>
        internal static string BidColor {
            get {
                return ResourceManager.GetString("BidColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bollinger bands.
        /// </summary>
        internal static string BollingerBands {
            get {
                return ResourceManager.GetString("BollingerBands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Candle Border.
        /// </summary>
        internal static string BorderColor {
            get {
                return ResourceManager.GetString("BorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bullish.
        /// </summary>
        internal static string Bullish {
            get {
                return ResourceManager.GetString("Bullish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Buys.
        /// </summary>
        internal static string Buys {
            get {
                return ResourceManager.GetString("Buys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calculation.
        /// </summary>
        internal static string Calculation {
            get {
                return ResourceManager.GetString("Calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calculation Mode.
        /// </summary>
        internal static string CalculationMode {
            get {
                return ResourceManager.GetString("CalculationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Candles.
        /// </summary>
        internal static string Candles {
            get {
                return ResourceManager.GetString("Candles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Commodity channel index.
        /// </summary>
        internal static string CCI {
            get {
                return ResourceManager.GetString("CCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changing Level Alert.
        /// </summary>
        internal static string ChangingLevelAlert {
            get {
                return ResourceManager.GetString("ChangingLevelAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Colors.
        /// </summary>
        internal static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Common.
        /// </summary>
        internal static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current day.
        /// </summary>
        internal static string CurrentDay {
            get {
                return ResourceManager.GetString("CurrentDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current month.
        /// </summary>
        internal static string CurrentMonth {
            get {
                return ResourceManager.GetString("CurrentMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current week.
        /// </summary>
        internal static string CurrentWeek {
            get {
                return ResourceManager.GetString("CurrentWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Daily.
        /// </summary>
        internal static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Days to save.
        /// </summary>
        internal static string DaysToSave {
            get {
                return ResourceManager.GetString("DaysToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delta.
        /// </summary>
        internal static string Delta {
            get {
                return ResourceManager.GetString("Delta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delta сoloring.
        /// </summary>
        internal static string DeltaColored {
            get {
                return ResourceManager.GetString("DeltaColored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Diamond.
        /// </summary>
        internal static string Diamondenum {
            get {
                return ResourceManager.GetString("Diamondenum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Negative directional indicator.
        /// </summary>
        internal static string DINeg {
            get {
                return ResourceManager.GetString("DINeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Positive directional indicator.
        /// </summary>
        internal static string DIPos {
            get {
                return ResourceManager.GetString("DIPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Down Candle Color.
        /// </summary>
        internal static string DownCandleColor {
            get {
                return ResourceManager.GetString("DownCandleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drawing.
        /// </summary>
        internal static string Drawing {
            get {
                return ResourceManager.GetString("Drawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Directional movement index.
        /// </summary>
        internal static string DX {
            get {
                return ResourceManager.GetString("DX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ellipse.
        /// </summary>
        internal static string Ellipse {
            get {
                return ResourceManager.GetString("Ellipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exponential moving average.
        /// </summary>
        internal static string EMA {
            get {
                return ResourceManager.GetString("EMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filters.
        /// </summary>
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First Dev..
        /// </summary>
        internal static string FirstDev {
            get {
                return ResourceManager.GetString("FirstDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fix maximum values.
        /// </summary>
        internal static string FixMaxValues {
            get {
                return ResourceManager.GetString("FixMaxValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Font Color.
        /// </summary>
        internal static string FontColor {
            get {
                return ResourceManager.GetString("FontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Full.
        /// </summary>
        internal static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Highest.
        /// </summary>
        internal static string Highest {
            get {
                return ResourceManager.GetString("Highest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на High/Low.
        /// </summary>
        internal static string HighLow {
            get {
                return ResourceManager.GetString("HighLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на History.
        /// </summary>
        internal static string HistorySaving {
            get {
                return ResourceManager.GetString("HistorySaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hourly.
        /// </summary>
        internal static string Hourly {
            get {
                return ResourceManager.GetString("Hourly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Left.
        /// </summary>
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Line.
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Linear regression.
        /// </summary>
        internal static string LinearReg {
            get {
                return ResourceManager.GetString("LinearReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Line style.
        /// </summary>
        internal static string LineDashStyle {
            get {
                return ResourceManager.GetString("LineDashStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lines.
        /// </summary>
        internal static string Lines {
            get {
                return ResourceManager.GetString("Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Levels limit.
        /// </summary>
        internal static string LivelsLimit {
            get {
                return ResourceManager.GetString("LivelsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Long period.
        /// </summary>
        internal static string LongPeriod {
            get {
                return ResourceManager.GetString("LongPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lowest.
        /// </summary>
        internal static string Lowest {
            get {
                return ResourceManager.GetString("Lowest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Moving average convergence/divergence.
        /// </summary>
        internal static string MACD {
            get {
                return ResourceManager.GetString("MACD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum volume.
        /// </summary>
        internal static string MaxVolume {
            get {
                return ResourceManager.GetString("MaxVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mean deviation.
        /// </summary>
        internal static string MeanDeviation {
            get {
                return ResourceManager.GetString("MeanDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimize Mode.
        /// </summary>
        internal static string Minimizedmode {
            get {
                return ResourceManager.GetString("Minimizedmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum volume.
        /// </summary>
        internal static string MinVolume {
            get {
                return ResourceManager.GetString("MinVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mode.
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Momentum.
        /// </summary>
        internal static string Momentum {
            get {
                return ResourceManager.GetString("Momentum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Monthly.
        /// </summary>
        internal static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Multiplier.
        /// </summary>
        internal static string Multiplier {
            get {
                return ResourceManager.GetString("Multiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OffsetMultiplier.
        /// </summary>
        internal static string OffsetMultiplier {
            get {
                return ResourceManager.GetString("OffsetMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only price.
        /// </summary>
        internal static string OnlyCluster {
            get {
                return ResourceManager.GetString("OnlyCluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Panel.
        /// </summary>
        internal static string Panel {
            get {
                return ResourceManager.GetString("Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ParabolicSAR.
        /// </summary>
        internal static string ParabolicSAR {
            get {
                return ResourceManager.GetString("ParabolicSAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Period.
        /// </summary>
        internal static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pivot Range.
        /// </summary>
        internal static string PivotRange {
            get {
                return ResourceManager.GetString("PivotRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Previous day.
        /// </summary>
        internal static string PreviousDay {
            get {
                return ResourceManager.GetString("PreviousDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Previous month.
        /// </summary>
        internal static string PreviousMonth {
            get {
                return ResourceManager.GetString("PreviousMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Previous week.
        /// </summary>
        internal static string PreviousWeek {
            get {
                return ResourceManager.GetString("PreviousWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rectangle.
        /// </summary>
        internal static string Rectangle {
            get {
                return ResourceManager.GetString("Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Right.
        /// </summary>
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Relative strength index.
        /// </summary>
        internal static string RSI {
            get {
                return ResourceManager.GetString("RSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Relative vigor index.
        /// </summary>
        internal static string RVI {
            get {
                return ResourceManager.GetString("RVI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save history.
        /// </summary>
        internal static string SaveHistory {
            get {
                return ResourceManager.GetString("SaveHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scale.
        /// </summary>
        internal static string ScaleIt {
            get {
                return ResourceManager.GetString("ScaleIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Second Dev..
        /// </summary>
        internal static string SecondDev {
            get {
                return ResourceManager.GetString("SecondDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sells.
        /// </summary>
        internal static string Sells {
            get {
                return ResourceManager.GetString("Sells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Session delta mode.
        /// </summary>
        internal static string SessionDeltaMode {
            get {
                return ResourceManager.GetString("SessionDeltaMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Short period.
        /// </summary>
        internal static string ShortPeriod {
            get {
                return ResourceManager.GetString("ShortPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show value.
        /// </summary>
        internal static string ShowCurrentValue {
            get {
                return ResourceManager.GetString("ShowCurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show description of indicator.
        /// </summary>
        internal static string ShowDescription {
            get {
                return ResourceManager.GetString("ShowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ShowVolume.
        /// </summary>
        internal static string ShowVolume {
            get {
                return ResourceManager.GetString("ShowVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show zero values.
        /// </summary>
        internal static string ShowZeroValue {
            get {
                return ResourceManager.GetString("ShowZeroValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Moving average.
        /// </summary>
        internal static string SMA {
            get {
                return ResourceManager.GetString("SMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Smoothed moving average.
        /// </summary>
        internal static string SMMA {
            get {
                return ResourceManager.GetString("SMMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Smooth.
        /// </summary>
        internal static string Smooth {
            get {
                return ResourceManager.GetString("Smooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Source.
        /// </summary>
        internal static string SourceDataSeries {
            get {
                return ResourceManager.GetString("SourceDataSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Standard deviation.
        /// </summary>
        internal static string StdDev {
            get {
                return ResourceManager.GetString("StdDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stochastic.
        /// </summary>
        internal static string Stochastic {
            get {
                return ResourceManager.GetString("Stochastic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text location.
        /// </summary>
        internal static string TextLocation {
            get {
                return ResourceManager.GetString("TextLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text size.
        /// </summary>
        internal static string TextSize {
            get {
                return ResourceManager.GetString("TextSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ticks.
        /// </summary>
        internal static string Ticks {
            get {
                return ResourceManager.GetString("Ticks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time filter, sec.
        /// </summary>
        internal static string TimeFilterSec {
            get {
                return ResourceManager.GetString("TimeFilterSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trades Filter.
        /// </summary>
        internal static string TradesFilter {
            get {
                return ResourceManager.GetString("TradesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Triangle.
        /// </summary>
        internal static string Triangle {
            get {
                return ResourceManager.GetString("Triangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Up Candle Color.
        /// </summary>
        internal static string UpCandleColor {
            get {
                return ResourceManager.GetString("UpCandleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Использовать алерты.
        /// </summary>
        internal static string UseAlerts {
            get {
                return ResourceManager.GetString("UseAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use filter.
        /// </summary>
        internal static string UseFilter {
            get {
                return ResourceManager.GetString("UseFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable proportional height.
        /// </summary>
        internal static string UseHeightFactor {
            get {
                return ResourceManager.GetString("UseHeightFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Visible.
        /// </summary>
        internal static string Visible {
            get {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mode.
        /// </summary>
        internal static string VisualMode {
            get {
                return ResourceManager.GetString("VisualMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Visual type.
        /// </summary>
        internal static string VisualType {
            get {
                return ResourceManager.GetString("VisualType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Volume.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Volume Visualization Type.
        /// </summary>
        internal static string VolumeVisualizationType {
            get {
                return ResourceManager.GetString("VolumeVisualizationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weekly.
        /// </summary>
        internal static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Width.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weighted moving average.
        /// </summary>
        internal static string WMA {
            get {
                return ResourceManager.GetString("WMA", resourceCulture);
            }
        }
    }
}
